module.exports = {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {},
  },
  corePlugins: {
    aspectRatio: false,
  },
  plugins: [
    require('@tailwindcss/typography'),
    require('@tailwindcss/aspect-ratio'),
    require('@tailwindcss/container-queries'),
    require('@tailwindcss/forms'),
    require('daisyui'),
    require('@tailwindcss/line-clamp'),
  ],
  daisyui: {
    styled: true,
    themes: [
      {
        richardson: {
          'color-scheme': 'light',
          primary: 'hsl(258, 62%, 19%)',
          'primary-content': 'hsl(0, 0%, 100%)',
          secondary: 'hsl(259, 29%, 39%)',
          'secondary-content': 'hsl(0, 0%, 100%)',
          accent: 'hsl(209, 42%, 53%)',
          'accent-content': 'hsl(0, 0%, 0%)',
          neutral: 'hsl(207, 17%, 88%)',
          'neutral-content': 'hsl(0, 0%, 0%)',
          'base-100': 'hsl(0, 0%, 100%)',
          'base-200': 'hsl(207, 17%, 88%)',
          'base-300': 'hsl(0, 0%, 58%)',
          'base-content': 'hsl(0, 0%, 0%)',
          info: 'hsl(192, 39%, 85%)',
          success: 'hsl(74, 76%, 79%)',
          warning: 'hsl(50, 87%, 75%)',
          error: 'hsl(1, 70%, 83%)',
          'info-content': 'hsl(192, 39%, 35%)',
          'success-content': 'hsl(74, 76%, 35%)',
          'warning-content': 'hsl(50, 87%, 35%)',
          'error-content': 'hsl(1, 50%, 35%)',
          '--rounded-box': '0.25rem',
          '--rounded-btn': '0.75rem',
          '--rounded-badge': '0.5rem',
          '--animation-btn': '0',
          '--animation-input': '0',
          '--btn-focus-scale': '1',
          '--tab-radius': '0',
        },
      },
      'light',
      'dark',
      'lemonade',
      'cyberpunk',
      'night',
      'luxury',
      'lofi',
      'wireframe',
    ],
    base: true,
    utils: true,
    logs: true,
    rtl: false,
    prefix: '',
    darkTheme: 'luxury',
  },
}
